### ISSUE TITLE
Error level error does not work

### ISSUE THREAD

**Issue by FuwenChen** [studiometa/prettier-formatter-gitlab#42]
![image](https://github.com/user-attachments/assets/a06fb05e-c986-4e0d-92b8-4e52016683eb)

**Comment by titouanmathis** [comment]
@FuwenChen could you please try the 2.1.0-alpha.1 version to see if it works correctly?

**Comment by FuwenChen** [comment]
> @FuwenChen could you please try the 2.1.0-alpha.1 version to see if it works correctly?

It's working normally
